name: deploy on github page
run-name: ${{ github.actor }} is deploying on github page

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run build
